# Generated by Django 5.2.7 on 2026-01-15 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('domain', models.CharField(max_length=255)),
                ('raw_content', models.TextField()),
                ('normalized_text', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClipLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clips.clip')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clips.label')),
            ],
        ),
        migrations.AddField(
            model_name='clip',
            name='labels',
            field=models.ManyToManyField(related_name='clips', through='clips.ClipLabel', to='clips.label'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_label_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cliplabel',
            constraint=models.UniqueConstraint(fields=('clip', 'label'), name='uniq_clip_label'),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['user', 'created_at'], name='clips_clip_user_id_f4b179_idx'),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['user', 'domain'], name='clips_clip_user_id_680d9b_idx'),
        ),
    ]
